name: flutter_forge_2026_grand_opening
description: Flutter Forge 2026 - 4 Hour Grand Opening Countdown
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/background_campus.png
    - assets/college_logo.png
